server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    user:
      name: "provider.user@provider.com"
      password: "{noop}password"
      roles: "USER"
    oauth2:
      authorizationserver:
        client:
          bulk-claim-client:
            registration:
              client-id: "bulk-claim-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8082/login/oauth2/code/silas-identity"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8082/logged-out"
              scopes:
                - "openid"
                - "profile"
                - "email"


